### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Piyush-555** [amazonqa/amazonqa#3]
Hi,
I am trying to reproduce your results. I am getting that, first `src/prepo/preprocess_data.sh` is to be run. Then `src/prepr/create_data.sh` is to be run. But, I am not getting how `model_answerable.pkl` is getting created. Also, how is `final_annotated_data.csv` used in `src/mturk/QuestionClassificationSuggestive.ipynb` is created?

**Comment by amazonqa** [comment]
Thank for your interest in the dataset. We have updated the readme with the answerability classifier files.

**Comment by Piyush-555** [comment]
Thanks!
