### ISSUE TITLE
Where are the test sets for Processed Dataset?

### ISSUE THREAD

**Issue by jshin49** [amazonqa/amazonqa#6]
First, thanks for sharing this resource.

But, I have a few questions regarding how to use this resource.

1. What is the intended purpose of this dataset? Is it for span extraction, or answer generation?
2. Where is the test set of the 'Processed Data' format?
3. What is the sequence of preprocessing?

Thanks.

**Comment by rchanda** [comment]
Hi, we have uploaded the test dataset for all formats now. Please check the links [here](https://github.com/amazonqa/amazonqa#updates).
